Repository OpenSlides/openslides-datastore-service, pull requests merged in 2022-05, with the labels that each got.

#196 Add new operator for case insensitivity
  datastore/shared/postgresql_backend/sql_query_helper.py
  datastore/shared/util/filter.py
  tests/reader/system/filter/test_filter.py
Labels: feature, high

#195 Issue191 multiple transaction error
  datastore/shared/postgresql_backend/pg_connection_handler.py
  dc.test.yml
  requirements/requirements-testing.txt
  tests/reader/system/test_client.py
  tests/shared/integration/__init__.py
  tests/shared/integration/postgresql_backend/__init__.py
  tests/shared/integration/postgresql_backend/test_pg_connection_handler.py
  tests/shared/unit/postgresql_backend/test_pg_connection_handler.py
Labels: bug, high

#198 Compare by numeric value instead of string value
  datastore/shared/postgresql_backend/sql_query_helper.py
  tests/reader/system/filter/test_filter.py
Labels: bug, blocker
