Repository OpenSlides/openslides-datastore-service, pull requests merged in 2022-04, with the labels that each got.

#185 Update to Python 3.10 and update dependencies
  Dockerfile
  Dockerfile.dev
  Dockerfile.test
  datastore/reader/core/reader_service.py
  datastore/shared/typing.py
  datastore/shared/util/self_validating_dataclass.py
  requirements/requirements-general.txt
  requirements/requirements-testing.txt
  scripts/ci/10-black.sh
  system_tests/Dockerfile
Labels: dependencies, feature

#189 Add AddFieldsMigration
  datastore/migrations/__init__.py
  datastore/migrations/migrations/add_field_migration.py
  datastore/migrations/migrations/add_fields_migration.py
  tests/migrations/system/test_premade_migration_classes.py
Labels: feature

#188 in-memory migration for meeting-import (Backend Issue1074)
  datastore/migrations/core/migrater.py
  datastore/migrations/core/migrater_memory.py
  datastore/migrations/core/migration_handler.py
  datastore/migrations/core/setup.py
  tests/migrations/system/conftest.py
  tests/migrations/system/test_memory_migration.py
Labels: feature, high
