Repository OpenSlides/openslides-datastore-service, pull requests merged in 2023-04, with the labels that each got.

#237 Update postgres to version 13
  dc.dev.yml
  dc.external.yml
  dc.test.yml
  docker-compose.yml
Labels: dependencies

#238 Ba issue1680 action worker deletion
  datastore/writer/core/database.py
  datastore/writer/core/writer_service.py
  datastore/writer/flask_frontend/routes_handler.py
  datastore/writer/postgresql_backend/sql_database_backend_service.py
  tests/writer/system/test_write_action_worker.py
Labels: feature

#241 Remove noqa comments from init files and add global flake8 rule
  datastore/__init__.py
  datastore/migrations/__init__.py
  datastore/reader/__init__.py
  datastore/reader/core/__init__.py
  datastore/reader/flask_frontend/__init__.py
  datastore/shared/di/__init__.py
  datastore/shared/flask_frontend/__init__.py
  datastore/shared/postgresql_backend/__init__.py
  datastore/shared/services/__init__.py
  datastore/shared/util/__init__.py
  datastore/writer/__init__.py
  datastore/writer/core/__init__.py
  datastore/writer/flask_frontend/__init__.py
  datastore/writer/postgresql_backend/__init__.py
  datastore/writer/redis_backend/__init__.py
  scripts/setup.cfg
  tests/__init__.py
Labels: clean up
