Repository OpenSlides/openslides-datastore-service, pull requests merged in 2023-01, with the labels that each got.

#221 Rename postgresql to postgres
  README.md
  dc.dev.yml
  dc.external.yml
  dc.test.yml
  docker-compose.yml
  scripts/psql.sh
  scripts/system/export-database-variables.sh
Labels: clean up

#225 Copy scripts into dev container
  Dockerfile.dev
Labels: feature

#227 Add workflow to automatically set project
  .github/workflows/set-project.yml
Labels: enhancement

#220 #219 database failover and prolonged retry_on_db_failure
  README.md
  datastore/shared/postgresql_backend/pg_connection_handler.py
  tests/shared/unit/postgresql_backend/test_pg_connection_handler.py
Labels: feature

#223 Issue222 In-memory-migration with less memory consumption
  datastore/migrations/core/migrater_memory.py
Labels: high
